### PR TITLE
Updating angulac cli to node 8

### PR DESCRIPTION
**Pull request by karllhughes**
I believe this addresses #32.

It works for me, but I'm not sure if you have a more robust method for testing this Dockerfile? If so, let me know how to proceed.

### CODE REVIEW

**Comment by karllhughes** [comment]
Now I'm having issues with my Angular tests @hoatle. Maybe we should hold off. Here's the error I get:

```
24 07 2017 14:11:10.309:ERROR [config]: Error in config file!
 TypeError: Invalid Version: https://registry.npmjs.org/istanbul-lib-instrument/-/istanbul-lib-instrument-1.7.4.tgz
    at new SemVer (/angular/node_modules/semver/semver.js:293:11)
    at major (/angular/node_modules/semver/semver.js:551:10)
    at Object.<anonymous> (/angular/node_modules/istanbul-lib-instrument/dist/constants.js:19:117)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/angular/node_modules/istanbul-lib-instrument/dist/visitor.js:11:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

Can you see if it gives you this error as well? It might just be that I've got something configured wrong on my end.

**Comment by hoatle** [comment]
thank you, I will check the errors soon.

**Comment by karllhughes** [comment]
Another quick update. Running tests worked fine for me without Istanbul reporting enabled, so I'm going to try updating versions of that and see if it fixes things.

**Comment by karllhughes** [comment]
I updated all my dev packages to the latest versions and was able to run tests with istanbul coverage.

The problem is that my Angular CLI app has been around since the early days, so many of the dependencies have been updated for new apps, but I haven't always updated immediately. I was one major version behind on `karma-coverage-istanbul-reporter` and that's what caused my tests to fail.

This seems to be working for me now.

**Comment by karllhughes** [comment]
I've been using this for the past couple weeks without issue now. If there's anything else I can do to test it please let me know. Thanks!

**Comment by hoatle** [comment]
thank you @karllhughes for testing, let me review and verify then.

**Comment by hoatle** [comment]
@karllhughes: the new Docker image should be available, please update and let me know if there is any problem then, thank you.

**Comment by karllhughes** [comment]
Awesome, thanks for maintaining this @hoatle!

**Pull request merged**
